/*
  NETZUN.COM
  INSTRUCTOR: MIKE NIEVA
  JAVASCRIPT BÁSICO

  MÓDULO 2
  CÁPSULA 1. "SINTAXIS DE OBJETOS"
*/

//============EJERCICIOS============//
//==================================//
//==================================//


//==================================//
/* 
  EJERCICIO 1: CREA UN OBJETO "MASCOTA" QUE INCLUYA AL MENOS 5 PROPIEDADES. 
  DE PREFERENCIA, MEZCLA EL VALOR CON DIFERENTES TIPOS DE DATOS (STRINGS, NUMBER, BOOLEAN, OTRO OBJETO, UN ARREGLO)
*/



//================= =================//
/* 
  EJERCICIO 2: CREA UN OBJETO "SCHOOL" QUE INCLUYA 3 PROPIEDADES CON UN TIPO DE DATO ESPECÍFICO:
  A) NAME (STRING)
  B) AVAILABILITY (OBJECT)
    - MORNINGS (BOOLEAN)
    - AFTERNOONS (BOOLEAN)
  C) COST (NUMBER)

  UNA VEZ REALIZADO EL OBJETO, ACCEDE AL VALOR DE "MORNINGS" A TRAVÉS "DOT NOTATION" Y "BRACKET NOTATION". AMBOS.

*/


//==================================//
/* 
  EJERCICIO 3: CREA UN OBJETO "PERRO" QUE CONTENGA 2 PROPIEDADES Y UN MÉTODO.
  A) NAME (STRING)
  B) COLOR (STRING)
  C) BARK (FUNCTION)
*/

