/*
  NETZUN.COM
  INSTRUCTOR: MIKE NIEVA
  JAVASCRIPT BÁSICO

  MÓDULO 1
  CÁPSULA 5. "FUNCIONES"
*/

//============EJERCICIOS============//
//==================================//
//==================================//


//==================================//
/* 
  EJERCICIO 1: COMIENZA DECLARANDO UNA FUNCIÓN QUE SUME DOS VARIABLES. INCLUYE DOS PARÁMETROS Y QUE AMBOS SE SUMEN ENTRE ELLOS:
  A) NUMA. TIPO DE DATO NUMBER
  B) NUMB. TIPO DE DATO NUMBER

  UNA VEZ DECLARADA LA FUNCIÓN, RECUERDA INVOCARLA Y OBSERVAR EL RESULTADO CON UN CONSOLE.LOG().
*/


//================= =================//
/* 
  EJERCICIO 2: ESTABLECE UNA FUNCIÓN QUE DETERMINE DOS PARÁMETROS:
  A) NOMBRE. CON TIPO DE DATO STRING
  B) APELLIDO. CON TIPO DE DATO STRING

  Y, PERMITE QUE AMBOS SE CONCATENEN ENTRE ELLOS. UTILIZA EL OPERADOR DE SUMA PARA UNIR AMBOS TEXTOS. 
  RETORNA EL VALOR
*/


//==================================//
/* 
  EJERCICIO 3: ESTABLECE UNA FUNCIÓN QUE REALICE EL PROMEDIO DE 5 NÚMEROS. UTILIZA 5 PARAMETROS:
  A) CA. TIPO DE DATO NUMBER
  B) CB. TIPO DE DATO NUMBER
  C) CC. TIPO DE DATO NUMBER
  D) CD. TIPO DE DATO NUMBER
  E) CE. TIPO DE DATO NUMBER

  EL RESULTADO DEBE SER UN NÚMERO. RECUERDA AL INVOCAR, REVISAR TU RESULTADO CON CONSOLE.LOG().

*/
